spring:
  application:
    name:

  security:
    user:
      name: user
      password: password

  datasource:
    url: jdbc:mysql://152.69.229.186:3306/finpick
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secretKey: simplekey123
